# Generated by Django 6.0.7 on 2026-07-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={
                "ordering": ["username"],
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
            },
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="ativo",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="avatar_cor",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="avatar_sigla",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="ultimo_login_sti",
        ),
        migrations.AddField(
            model_name="usuario",
            name="identificador_aluno",
            field=models.CharField(
                blank=True,
                help_text="Vínculo com o registro do aluno no backend do Grupo 1. Usado nas chamadas à API, por exemplo /api/desempenho/<id>/. Deixar em branco para professores.",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Identificador do aluno (Grupo 1)",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="primeiro_acesso",
            field=models.BooleanField(
                default=True,
                help_text="Quando verdadeiro, o usuário é obrigado a trocar a senha no próximo login. Usado principalmente para professores cadastrados pelo administrador com senha temporária.",
                verbose_name="Primeiro acesso",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="papel",
            field=models.CharField(
                choices=[("aluno", "Aluno"), ("professor", "Professor")],
                default="aluno",
                help_text="Define o tipo de acesso do usuário no sistema.",
                max_length=20,
                verbose_name="Papel",
            ),
        ),
        migrations.AlterModelTable(
            name="usuario",
            table="usuario",
        ),
    ]
