# Generated by Django 6.0.7 on 2026-07-16 18:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conquista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=60, unique=True, verbose_name="Codigo"),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("descricao", models.TextField(blank=True, verbose_name="Descricao")),
                (
                    "icone",
                    models.CharField(blank=True, max_length=10, verbose_name="Icone"),
                ),
                (
                    "xp_bonus",
                    models.SmallIntegerField(default=0, verbose_name="XP bonus"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Conquista",
                "verbose_name_plural": "Conquistas",
            },
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=80, unique=True, verbose_name="Nome"),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descricao")),
                (
                    "icone",
                    models.CharField(blank=True, max_length=10, verbose_name="Icone"),
                ),
                (
                    "cor_primaria",
                    models.CharField(
                        default="#1a73e8", max_length=40, verbose_name="Cor primaria"
                    ),
                ),
                (
                    "prompt_sistema",
                    models.TextField(blank=True, verbose_name="Prompt do sistema"),
                ),
                ("ordem", models.SmallIntegerField(default=0, verbose_name="Ordem")),
                ("ativa", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Questao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enunciado", models.TextField(verbose_name="Enunciado")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("multipla", "Multipla escolha"),
                            ("verdadeiro_falso", "Verdadeiro ou Falso"),
                            ("dissertativa", "Dissertativa"),
                        ],
                        default="multipla",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("explicacao", models.TextField(blank=True, verbose_name="Explicacao")),
                (
                    "ordem",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
            ],
            options={
                "verbose_name": "Questao",
                "verbose_name_plural": "Questoes",
                "ordering": ["quiz", "ordem"],
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "papel",
                    models.CharField(
                        choices=[("aluno", "Aluno"), ("professor", "Professor")],
                        default="aluno",
                        max_length=20,
                        verbose_name="Papel",
                    ),
                ),
                (
                    "avatar_sigla",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="Sigla do avatar"
                    ),
                ),
                (
                    "avatar_cor",
                    models.CharField(
                        blank=True,
                        default="#1a73e8",
                        max_length=40,
                        verbose_name="Cor do avatar",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "ultimo_login_sti",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ultimo login no STI"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Licao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150, verbose_name="Titulo")),
                ("descricao", models.TextField(blank=True, verbose_name="Descricao")),
                ("conteudo", models.TextField(blank=True, verbose_name="Conteudo")),
                ("ordem", models.SmallIntegerField(default=0, verbose_name="Ordem")),
                (
                    "total_etapas",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Total de etapas"
                    ),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licoes",
                        to="app.disciplina",
                        verbose_name="Disciplina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Licao",
                "verbose_name_plural": "Licoes",
                "ordering": ["disciplina", "ordem"],
            },
        ),
        migrations.CreateModel(
            name="Conversa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(blank=True, max_length=200, verbose_name="Titulo"),
                ),
                (
                    "total_mensagens",
                    models.SmallIntegerField(
                        default=0, verbose_name="Total de mensagens"
                    ),
                ),
                (
                    "tokens_usados",
                    models.IntegerField(default=0, verbose_name="Tokens usados"),
                ),
                (
                    "iniciada_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Iniciada em"),
                ),
                (
                    "encerrada_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Encerrada em"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversas",
                        to="app.disciplina",
                        verbose_name="Disciplina",
                    ),
                ),
                (
                    "licao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversas",
                        to="app.licao",
                        verbose_name="Licao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversa",
                "verbose_name_plural": "Conversas",
                "ordering": ["-iniciada_em"],
            },
        ),
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "papel",
                    models.CharField(
                        choices=[("aluno", "Aluno"), ("tutor", "Tutor")],
                        max_length=10,
                        verbose_name="Papel",
                    ),
                ),
                ("conteudo", models.TextField(verbose_name="Conteudo")),
                ("tokens", models.SmallIntegerField(default=0, verbose_name="Tokens")),
                (
                    "enviado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Enviado em"),
                ),
                (
                    "conversa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to="app.conversa",
                        verbose_name="Conversa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem",
                "verbose_name_plural": "Mensagens",
                "ordering": ["enviado_em"],
            },
        ),
        migrations.CreateModel(
            name="NivelUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xp_total", models.IntegerField(default=0, verbose_name="XP total")),
                ("nivel", models.SmallIntegerField(default=1, verbose_name="Nivel")),
                (
                    "xp_proximo_nivel",
                    models.IntegerField(
                        default=100, verbose_name="XP para o proximo nivel"
                    ),
                ),
                (
                    "streak_dias",
                    models.SmallIntegerField(
                        default=0, verbose_name="Sequencia de dias"
                    ),
                ),
                (
                    "ultima_atividade",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ultima atividade"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nivel",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nivel do Usuario",
                "verbose_name_plural": "Niveis dos Usuarios",
            },
        ),
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=40, verbose_name="Tipo")),
                ("titulo", models.CharField(max_length=120, verbose_name="Titulo")),
                ("corpo", models.TextField(blank=True, verbose_name="Corpo")),
                (
                    "link",
                    models.URLField(blank=True, max_length=300, verbose_name="Link"),
                ),
                ("lida", models.BooleanField(default=False, verbose_name="Lida")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "lida_em",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lida em"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificacao",
                "verbose_name_plural": "Notificacoes",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Alternativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField(verbose_name="Texto")),
                ("correta", models.BooleanField(default=False, verbose_name="Correta")),
                (
                    "ordem",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
                (
                    "questao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternativas",
                        to="app.questao",
                        verbose_name="Questao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alternativa",
                "verbose_name_plural": "Alternativas",
                "ordering": ["questao", "ordem"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Titulo")),
                ("descricao", models.TextField(blank=True, verbose_name="Descricao")),
                (
                    "total_questoes",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Total de questoes"
                    ),
                ),
                (
                    "gerado_por_ia",
                    models.BooleanField(default=False, verbose_name="Gerado por IA"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quizzes",
                        to="app.disciplina",
                        verbose_name="Disciplina",
                    ),
                ),
                (
                    "licao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quizzes",
                        to="app.licao",
                        verbose_name="Licao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizzes",
            },
        ),
        migrations.AddField(
            model_name="questao",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questoes",
                to="app.quiz",
                verbose_name="Quiz",
            ),
        ),
        migrations.CreateModel(
            name="TentativaQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acertos",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Acertos"),
                ),
                (
                    "total",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Total"),
                ),
                (
                    "pontuacao",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Pontuacao",
                    ),
                ),
                (
                    "xp_ganho",
                    models.SmallIntegerField(default=0, verbose_name="XP ganho"),
                ),
                (
                    "iniciado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Iniciado em"),
                ),
                (
                    "concluido_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluido em"
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tentativas",
                        to="app.quiz",
                        verbose_name="Quiz",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tentativas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tentativa de Quiz",
                "verbose_name_plural": "Tentativas de Quiz",
                "ordering": ["-iniciado_em"],
            },
        ),
        migrations.CreateModel(
            name="RespostaQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resposta_texto",
                    models.TextField(blank=True, verbose_name="Resposta dissertativa"),
                ),
                ("correta", models.BooleanField(default=False, verbose_name="Correta")),
                (
                    "respondido_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Respondido em"
                    ),
                ),
                (
                    "alternativa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="respostas",
                        to="app.alternativa",
                        verbose_name="Alternativa escolhida",
                    ),
                ),
                (
                    "questao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="app.questao",
                        verbose_name="Questao",
                    ),
                ),
                (
                    "tentativa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="app.tentativaquiz",
                        verbose_name="Tentativa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta de Quiz",
                "verbose_name_plural": "Respostas de Quiz",
            },
        ),
        migrations.CreateModel(
            name="Videoaula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Titulo")),
                ("descricao", models.TextField(blank=True, verbose_name="Descricao")),
                (
                    "url_youtube",
                    models.URLField(max_length=500, verbose_name="Link do YouTube"),
                ),
                (
                    "duracao_minutos",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Duracao (minutos)"
                    ),
                ),
                (
                    "ordem",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "cadastrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videoaulas_cadastradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cadastrado por",
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videoaulas",
                        to="app.disciplina",
                        verbose_name="Disciplina",
                    ),
                ),
                (
                    "licao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videoaulas",
                        to="app.licao",
                        verbose_name="Licao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Videoaula",
                "verbose_name_plural": "Videoaulas",
                "ordering": ["disciplina", "licao", "ordem"],
            },
        ),
        migrations.CreateModel(
            name="ConquistaUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ganho_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ganho em"),
                ),
                (
                    "conquista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios",
                        to="app.conquista",
                        verbose_name="Conquista",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conquistas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conquista do Usuario",
                "verbose_name_plural": "Conquistas dos Usuarios",
                "unique_together": {("usuario", "conquista")},
            },
        ),
        migrations.CreateModel(
            name="ProgressoLicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etapa_atual",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Etapa atual"
                    ),
                ),
                (
                    "concluida",
                    models.BooleanField(default=False, verbose_name="Concluida"),
                ),
                (
                    "xp_ganho",
                    models.SmallIntegerField(default=0, verbose_name="XP ganho"),
                ),
                (
                    "iniciado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Iniciado em"),
                ),
                (
                    "concluido_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluido em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "licao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progressos",
                        to="app.licao",
                        verbose_name="Licao",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progressos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progresso de Licao",
                "verbose_name_plural": "Progressos de Licoes",
                "ordering": ["-atualizado_em"],
                "unique_together": {("usuario", "licao")},
            },
        ),
    ]
