# Generated by Django 6.0.7 on 2026-07-24 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_usuario_options_remove_usuario_ativo_and_more"),
        ("banco_dados", "0004_delete_videoaula"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoaula",
            name="topico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="videoaulas",
                to="banco_dados.conteudoalgoritmos",
                verbose_name="Topico da base de conhecimento",
            ),
        ),
    ]
