# Generated by Django 6.1 on 2026-08-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_videoaula_topico'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='notificacoes_email',
            field=models.BooleanField(default=True, help_text='Receber avisos de novas conquistas, quizzes e atividades por e-mail.', verbose_name='Notificações por e-mail'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tema',
            field=models.CharField(choices=[('claro', 'Claro'), ('escuro', 'Escuro')], default='claro', help_text='Aparência escolhida pelo usuário (claro ou escuro).', max_length=10, verbose_name='Tema do site'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='turma_nome',
            field=models.CharField(blank=True, default='', help_text='Nome da turma exibido no painel do professor.', max_length=100, verbose_name='Turma (professor)'),
        ),
    ]
