# Generated by Django 6.1 on 2026-08-24 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usuario_notificacoes_email_usuario_tema_and_more'),
        ('banco_dados', '0004_delete_videoaula'),
    ]

    operations = [
        migrations.AddField(
            model_name='conquista',
            name='categoria',
            field=models.CharField(choices=[('inicio', 'Primeiros passos'), ('consistencia', 'Consistência'), ('conversas', 'Conversas com o tutor'), ('licoes', 'Lições'), ('quizzes', 'Quizzes'), ('exercicios', 'Exercícios'), ('progressao', 'Nível & XP'), ('geral', 'Geral')], default='geral', max_length=20, verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='RespostaExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField(blank=True, verbose_name='Resposta enviada')),
                ('correta', models.BooleanField(default=False, verbose_name='Resposta correta')),
                ('tentativas', models.PositiveSmallIntegerField(default=1, verbose_name='Tentativas')),
                ('respondido_em', models.DateTimeField(auto_now=True, verbose_name='Respondido em')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_alunos', to='banco_dados.exercicio', verbose_name='Exercício')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_exercicios', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Resposta de exercício',
                'verbose_name_plural': 'Respostas de exercícios',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'exercicio'), name='unico_resposta_por_aluno_exercicio')],
            },
        ),
    ]
