# Generated by Django 6.1 on 2026-08-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_conquista_categoria_respostaexercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar_cor',
            field=models.CharField(choices=[('azul', 'Azul'), ('verde', 'Verde'), ('roxo', 'Roxo'), ('laranja', 'Laranja'), ('rosa', 'Rosa')], default='azul', help_text='Cor do círculo com as iniciais exibido na barra lateral.', max_length=10, verbose_name='Cor do avatar'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reduzir_animacoes',
            field=models.BooleanField(default=False, help_text='Desativa transições e animações da interface (acessibilidade).', verbose_name='Reduzir animações'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='turma_codigo',
            field=models.CharField(blank=True, default='', help_text='Código ou identificador interno da turma, se houver.', max_length=30, verbose_name='Código da turma (professor)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='turma_turno',
            field=models.CharField(blank=True, choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('integral', 'Integral')], default='', max_length=10, verbose_name='Turno da turma (professor)'),
        ),
    ]
