# Generated by Django 6.0.7 on 2026-09-14 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_usuario_avatar_cor_usuario_reduzir_animacoes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="disciplina_atual",
            field=models.ForeignKey(
                blank=True,
                help_text="Disciplina à qual o aluno está vinculado.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alunos",
                to="app.disciplina",
                verbose_name="Disciplina atual",
            ),
        ),
    ]
