# Generated by Django 5.2.14 on 2026-06-10 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banco_dados", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConteudoAlgoritmos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=150, verbose_name="Título do tópico"),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Descrição breve"
                    ),
                ),
                (
                    "conteudo",
                    models.TextField(
                        blank=True, verbose_name="Conteúdo / material explicativo"
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("iniciante", "Iniciante"),
                            ("intermediario", "Intermediário"),
                            ("avancado", "Avançado"),
                        ],
                        default="iniciante",
                        max_length=20,
                        verbose_name="Nível",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem na trilha"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "pre_requisito",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="desbloqueia",
                        to="banco_dados.conteudoalgoritmos",
                        verbose_name="Pré-requisito",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conteúdo (Algoritmos)",
                "verbose_name_plural": "Conteúdos (Algoritmos)",
                "ordering": ["ordem", "titulo"],
            },
        ),
        migrations.CreateModel(
            name="Exercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enunciado", models.TextField(verbose_name="Enunciado do exercício")),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("iniciante", "Iniciante"),
                            ("intermediario", "Intermediário"),
                            ("avancado", "Avançado"),
                        ],
                        default="iniciante",
                        max_length=20,
                        verbose_name="Nível de dificuldade",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "topico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exercicios",
                        to="banco_dados.conteudoalgoritmos",
                        verbose_name="Tópico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercício",
                "verbose_name_plural": "Exercícios",
                "ordering": ["topico", "nivel"],
            },
        ),
        migrations.CreateModel(
            name="Gabarito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resposta_correta", models.TextField(verbose_name="Resposta correta")),
                ("explicacao", models.TextField(blank=True, verbose_name="Explicação")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "exercicio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gabarito",
                        to="banco_dados.exercicio",
                        verbose_name="Exercício",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gabarito",
                "verbose_name_plural": "Gabaritos",
            },
        ),
        migrations.CreateModel(
            name="RepositorioQA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pergunta", models.TextField(verbose_name="Pergunta")),
                (
                    "resposta",
                    models.TextField(verbose_name="Resposta validada pelo professor"),
                ),
                (
                    "palavras_chave",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Palavras-chave"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "topico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="perguntas",
                        to="banco_dados.conteudoalgoritmos",
                        verbose_name="Tópico relacionado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pergunta e Resposta (Q&A)",
                "verbose_name_plural": "Repositório de Q&A",
                "ordering": ["-atualizado_em"],
            },
        ),
    ]
