# Generated by Django 6.0.7 on 2026-07-20 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banco_dados", "0002_conteudoalgoritmos_exercicio_gabarito_repositorioqa"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicointeracoes",
            options={
                "ordering": ["-data_hora"],
                "verbose_name": "Historico de Interacao",
                "verbose_name_plural": "Historico de Interacoes",
            },
        ),
        migrations.AddField(
            model_name="historicointeracoes",
            name="fontes_rag",
            field=models.TextField(
                blank=True,
                help_text="Trechos do material do professor usados na resposta.",
                verbose_name="Fontes consultadas pelo RAG",
            ),
        ),
        migrations.AddField(
            model_name="historicointeracoes",
            name="usou_rag",
            field=models.BooleanField(
                default=False, verbose_name="Usou RAG (material do professor)"
            ),
        ),
        migrations.AlterField(
            model_name="historicointeracoes",
            name="resposta",
            field=models.TextField(verbose_name="Resposta do tutor"),
        ),
        migrations.AlterField(
            model_name="historicointeracoes",
            name="topico",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Topico / assunto"
            ),
        ),
        migrations.CreateModel(
            name="Videoaula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "url_youtube",
                    models.URLField(max_length=500, verbose_name="Link do YouTube"),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "topico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videoaulas",
                        to="banco_dados.conteudoalgoritmos",
                        verbose_name="Tópico relacionado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Videoaula",
                "verbose_name_plural": "Videoaulas",
                "ordering": ["topico", "titulo"],
            },
        ),
    ]
