# Generated by Django 6.0.7 on 2026-07-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banco_dados", "0003_alter_historicointeracoes_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Videoaula",
        ),
    ]
