# Generated by Django 5.2.14 on 2026-06-09 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PerfilAluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=120, verbose_name="Nome do aluno"),
                ),
                (
                    "identificador",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Matrícula ou identificador único",
                    ),
                ),
                (
                    "nivel_proficiencia",
                    models.CharField(
                        choices=[
                            ("iniciante", "Iniciante"),
                            ("intermediario", "Intermediário"),
                            ("avancado", "Avançado"),
                        ],
                        default="iniciante",
                        max_length=20,
                        verbose_name="Nível de proficiência atual",
                    ),
                ),
                (
                    "estilo_aprendizado",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        verbose_name="Estilo de aprendizado predominante",
                    ),
                ),
                (
                    "estado_emocional",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        verbose_name="Último estado emocional detectado",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Perfil do Aluno",
                "verbose_name_plural": "Perfis dos Alunos",
            },
        ),
        migrations.CreateModel(
            name="HistoricoInteracoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pergunta", models.TextField(verbose_name="Pergunta do aluno")),
                ("resposta", models.TextField(verbose_name="Resposta dada pelo tutor")),
                (
                    "topico",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Tópico / assunto"
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("regras", "IA Estruturada (regras) — sem custo"),
                            ("llm", "LLM em nuvem (Groq) — com custo"),
                        ],
                        default="regras",
                        max_length=10,
                        verbose_name="Origem da resposta",
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data e hora"),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interacoes",
                        to="banco_dados.perfilaluno",
                        verbose_name="Aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Interação",
                "verbose_name_plural": "Histórico de Interações",
                "ordering": ["-data_hora"],
            },
        ),
    ]
